[project]
name = "daily-journal"
version = "0.1.0"
description = "A daily journal that prints out daily"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=0.2.4",
    "langgraph>=0.2.41",
    "nba-api>=1.6.1",
]
